services:
  # Backend API service
  - type: web
    name: bedoui-backend
    runtime: node
    plan: free
    rootDir: ./backend
    buildCommand: >
      apt-get update && 
      apt-get install -y chromium && 
      npm ci --production && 
      npm cache clean --force
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: NODE_VERSION
        value: "20.x"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
      - key: FRONTEND_ORIGIN
        value: "*"
      - key: TVA_RATE
        value: "0.20"
      - key: DUPLICATE_WINDOW_SECONDS
        value: "15"
      - key: DOWNLOAD_TOKEN_TTL
        value: "3600"
      # Sensitive variables that need to be set in Render dashboard
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: BACKUP_ENCRYPTION_KEY
        sync: false
      - key: DOWNLOAD_TOKEN_SECRET
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: COMPANY_SIRET
        sync: false
      - key: COMPANY_APE
        sync: false
      - key: COMPANY_TVA
        sync: false
      - key: COMPANY_PHONE
        sync: false
      - key: COMPANY_EMAIL
        sync: false
      - key: COMPANY_SITE
        sync: false
      - key: COMPANY_LOGO_URL
        sync: false
      - key: DEVIS_NUMBER
        sync: false

  # Frontend service
  - type: web
    name: bedoui-frontend
    runtime: node
    plan: free
    rootDir: ./frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run preview
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.x"
      - key: PORT
        value: "10000"
      - key: VITE_BACKEND_URL
        sync: false
      - key: VITE_OAUTH_REDIRECT_URL
        sync: false
      # Sensitive variables that need to be set in Render dashboard
      - key: VITE_API_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_KEY
        sync: false








SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=firassmrabett111@gmail.com
SMTP_PASS=njzpoeqeclquosxy
API_KEY=Zyd9/Z2bg51ek+cX8OQQ+WrZQT+TRGKAdqeUdMqlqhE=
VITE_API_KEY=Zyd9/Z2bg51ek+cX8OQQ+WrZQT+TRGKAdqeUdMqlqhE=
ENCRYPTION_KEY=9a4decac9b508bb7fdbc556a96a189bae07ab99111d9e70ecb45b697bf03a169
BACKUP_ENCRYPTION_KEY=1da95a0060df569acca21708e1865b685d36dfb34e9683045072fd71b56ebed4
NODE_ENV=development
FRONTEND_ORIGIN=https://bedoui-firas-projects-e7e8a63d.vercel.app
VITE_SUPABASE_URL=https://ppwwttumnhgoymzcwfcc.supabase.co
VITE_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwd3d0dHVtbmhnb3ltemN3ZmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjU3NTEsImV4cCI6MjA3MDc0MTc1MX0.1vhw1ZF95fEyBCiNU69bYxdGwn1PjNUXabjHWlGtYQM
RECEIVER_EMAIL=firassmrabett111@gmail.com,marwenyoussef2017@gmail.com
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
PORT=5000
VITE_BACKEND_URL=http://localhost:5000